DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY (ID)
);

INSERT INTO PRODUCT(NAME) VALUES('TV');
INSERT INTO PRODUCT(NAME) VALUES('Table');
INSERT INTO PRODUCT(NAME) VALUES('Chair');
COMMIT;